# ============================================================
# Noctra OS - Kitty Matugen Color Template
# Processed by Matugen -> outputs to ~/.config/kitty/colors.conf
# ============================================================

# ── Base UI ──
background            #181115
foreground            #eddfe4
selection_background  #504349
selection_foreground  #d3c2c9

# ── Cursor ──
cursor                #fab1d9
cursor_text_color     #511d3e

# ── Tabs ──
active_tab_background   #fab1d9
active_tab_foreground   #511d3e
inactive_tab_background #504349
inactive_tab_foreground #d3c2c9
tab_bar_background      #181115

# ── The 16-Color ANSI Palette ──
# Black
color0  #181115
color8  #504349

# Red
color1  #ffb4ab
color9  #ffb4ab

# Green
color2  #fab1d9
color10 #fab1d9

# Yellow
color3  #f3ba9d
color11 #f3ba9d

# Blue
color4  #6b3456
color12 #6b3456

# Magenta
color5  #dfbecd
color13 #dfbecd

# Cyan
color6  #58404c
color14 #58404c

# White
color7  #eddfe4
color15 #d3c2c9