# ============================================================
# Noctra OS - Hyprland Dynamic Colors
# Processed by Matugen -> outputs to ~/.config/hypr/colors.conf
# ============================================================

$primary = rgb(fab1d9)
$secondary = rgb(dfbecd)
$tertiary = rgb(f3ba9d)
$surface = rgb(181115)
$error = rgb(ffb4ab)