# ============================================================
# Noctra OS - Hyprland Dynamic Colors
# Processed by Matugen -> outputs to ~/.config/hypr/colors.conf
# ============================================================

$primary = rgb(dcb9f8)
$secondary = rgb(d1c1d9)
$tertiary = rgb(f3b7bc)
$surface = rgb(151217)
$error = rgb(ffb4ab)