# ============================================================
# Noctra OS - Hyprland Dynamic Colors
# Processed by Matugen -> outputs to ~/.config/hypr/colors.conf
# ============================================================

$primary = rgb(f6b2e0)
$secondary = rgb(dcbed0)
$tertiary = rgb(f5b9a2)
$surface = rgb(181215)
$error = rgb(ffb4ab)