#############
### INPUT  ##
#############
input {
    kb_layout     = us
    follow_mouse  = 1
    sensitivity   = 0
    accel_profile = flat

    touchpad {
        natural_scroll       = true
        tap-to-click         = true
        drag_lock            = false
        disable_while_typing = true
    }
}

##############################
###        GESTURES        ###
##############################
# 3 fingers, swipe horizontally, switch workspace
gesture = 3, horizontal, workspace

# You can still fine-tune the feel inside a gestures block if needed:
gestures {
    workspace_swipe_distance = 200
    workspace_swipe_invert = false
}

