# ┌─────────────────────────────────────────────────────────────┐
# │                 Noctra OS - Layout Engines                  │
# └─────────────────────────────────────────────────────────────┘

dwindle {
    pseudotile = true 
    preserve_split = true 
    smart_split = false 
    smart_resizing = true 
}

master {
    new_status = master
    new_on_top = true
    mfact = 0.55
}