cursor #d2bcfd
cursor_text_color #38265c

active_tab_foreground   #38265c
active_tab_background   #d2bcfd
inactive_tab_foreground #cbc4cf
inactive_tab_background #49454e

foreground            #e7e0e8
background            #141218
selection_foreground  #e9def8
selection_background  #4b4358

color0  #141218
color8  #3b383e
color1  #ffb4ab
color9  #93000a
color2  #d2bcfd
color10 #4f3d74
color4  #f0b7c6
color12 #643b47
