cursor #acc7ff
cursor_text_color #0f2f60

active_tab_foreground   #0f2f60
active_tab_background   #acc7ff
inactive_tab_foreground #c4c6d0
inactive_tab_background #44474f

foreground            #e2e2e9
background            #111318
selection_foreground  #dae2f9
selection_background  #3f4759

color0  #111318
color8  #37393e
color1  #ffb4ab
color9  #93000a
color2  #acc7ff
color10 #2a4678
color4  #debcdf
color12 #583e5b
