[config]
swatches = true

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = "/home/blaze/.config/matugen/templates/kitty.conf"
output_path = "/home/blaze/.config/kitty/colors.conf"

[templates.cava]
input_path = "/home/blaze/.config/matugen/templates/cava"
output_path = "/home/blaze/.config/cava/config"

[templates.btop]
input_path = "/home/blaze/.config/matugen/templates/btop.theme"
output_path = "/home/blaze/.config/btop/themes/noctra.theme"

[templates.rofi]
input_path = "/home/blaze/.config/matugen/templates/rofi.rasi"
output_path = "/home/blaze/.config/rofi/colors.rasi"

[templates.fastfetch]
input_path = "/home/blaze/.config/matugen/templates/fastfetch.jsonc"
output_path = "/home/blaze/.config/fastfetch/config.jsonc"

[config.apps.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/colors.css'
# This command reloads SwayNC so colors apply instantly
post_command = 'swaync-client -rs'
