# ============================================================
# Noctra OS - Hyprlock Matugen Template
# Processed by Matugen -> outputs to ~/.config/hypr/hyprlock.conf
# ============================================================

background {
    monitor =
    # Use the current desktop as the background and blur it heavily
    path = screenshot
    color = {{colors.surface.default.hex}}
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    
    # Dynamic Matugen Colors
    outer_color = {{colors.primary.default.hex}}
    inner_color = {{colors.surface.default.hex}}
    font_color = {{colors.on_surface.default.hex}}
    check_color = {{colors.tertiary.default.hex}}
    fail_color = {{colors.error.default.hex}}
    
    fade_on_empty = false
    placeholder_text = <i><span foreground="##{{colors.on_surface_variant.default.hex_stripped}}">Enter Password...</span></i>
    hide_input = false
    
    position = 0, -100
    halign = center
    valign = center
}

# Clock 
label {
    monitor =
    text = $TIME
    color = {{colors.primary.default.hex}}
    font_size = 90
    font_family = JetBrainsMono Nerd Font Propo Bold
    position = 0, 100
    halign = center
    valign = center
}

# User Greeting
label {
    monitor =
    text = Hi there, $USER
    color = {{colors.secondary.default.hex}}
    font_size = 22
    font_family = JetBrainsMono Nerd Font Propo
    position = 0, 0
    halign = center
    valign = center
}